/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferenceAppRouteRouteImport } from './routes/reference-app/route'
import { Route as MainRouteRouteImport } from './routes/main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceAppAuthenticatedRouteRouteImport } from './routes/reference-app/_authenticated/route'
import { Route as MainAuthenticatedRouteRouteImport } from './routes/main/_authenticated/route'
import { Route as ReferenceAppAuthenticatedIndexRouteImport } from './routes/reference-app/_authenticated/index'
import { Route as MainAuthenticatedIndexRouteImport } from './routes/main/_authenticated/index'
import { Route as ReferenceAppAuthenticatedDashboardRouteImport } from './routes/reference-app/_authenticated/dashboard'
import { Route as ReferenceAppAuthenticatedComponentShowcaseRouteImport } from './routes/reference-app/_authenticated/component-showcase'
import { Route as ReferenceApperrors503RouteImport } from './routes/reference-app/(errors)/503'
import { Route as ReferenceApperrors500RouteImport } from './routes/reference-app/(errors)/500'
import { Route as ReferenceApperrors404RouteImport } from './routes/reference-app/(errors)/404'
import { Route as ReferenceApperrors403RouteImport } from './routes/reference-app/(errors)/403'
import { Route as ReferenceApperrors401RouteImport } from './routes/reference-app/(errors)/401'
import { Route as ReferenceAppauthSignUpRouteImport } from './routes/reference-app/(auth)/sign-up'
import { Route as ReferenceAppauthSignIn2RouteImport } from './routes/reference-app/(auth)/sign-in-2'
import { Route as ReferenceAppauthSignInRouteImport } from './routes/reference-app/(auth)/sign-in'
import { Route as ReferenceAppauthOtpRouteImport } from './routes/reference-app/(auth)/otp'
import { Route as ReferenceAppauthForgotPasswordRouteImport } from './routes/reference-app/(auth)/forgot-password'
import { Route as MainAuthenticatedNeo4jExplorerRouteImport } from './routes/main/_authenticated/neo4j-explorer'
import { Route as MainAuthenticatedDashboardRouteImport } from './routes/main/_authenticated/dashboard'
import { Route as Mainerrors503RouteImport } from './routes/main/(errors)/503'
import { Route as Mainerrors500RouteImport } from './routes/main/(errors)/500'
import { Route as Mainerrors404RouteImport } from './routes/main/(errors)/404'
import { Route as Mainerrors403RouteImport } from './routes/main/(errors)/403'
import { Route as Mainerrors401RouteImport } from './routes/main/(errors)/401'
import { Route as MainauthSignUpRouteImport } from './routes/main/(auth)/sign-up'
import { Route as MainauthSignIn2RouteImport } from './routes/main/(auth)/sign-in-2'
import { Route as MainauthSignInRouteImport } from './routes/main/(auth)/sign-in'
import { Route as MainauthOtpRouteImport } from './routes/main/(auth)/otp'
import { Route as MainauthForgotPasswordRouteImport } from './routes/main/(auth)/forgot-password'
import { Route as ReferenceAppAuthenticatedSettingsRouteRouteImport } from './routes/reference-app/_authenticated/settings/route'
import { Route as MainAuthenticatedSettingsRouteRouteImport } from './routes/main/_authenticated/settings/route'
import { Route as ReferenceAppAuthenticatedUsersIndexRouteImport } from './routes/reference-app/_authenticated/users/index'
import { Route as ReferenceAppAuthenticatedTasksIndexRouteImport } from './routes/reference-app/_authenticated/tasks/index'
import { Route as ReferenceAppAuthenticatedSettingsIndexRouteImport } from './routes/reference-app/_authenticated/settings/index'
import { Route as ReferenceAppAuthenticatedKfzMarktplatzIndexRouteImport } from './routes/reference-app/_authenticated/kfz-marktplatz/index'
import { Route as ReferenceAppAuthenticatedHelpCenterIndexRouteImport } from './routes/reference-app/_authenticated/help-center/index'
import { Route as ReferenceAppAuthenticatedChatsIndexRouteImport } from './routes/reference-app/_authenticated/chats/index'
import { Route as ReferenceAppAuthenticatedAppsIndexRouteImport } from './routes/reference-app/_authenticated/apps/index'
import { Route as MainAuthenticatedSettingsIndexRouteImport } from './routes/main/_authenticated/settings/index'
import { Route as MainAuthenticatedHelpCenterIndexRouteImport } from './routes/main/_authenticated/help-center/index'
import { Route as ReferenceAppAuthenticatedSettingsNotificationsRouteImport } from './routes/reference-app/_authenticated/settings/notifications'
import { Route as ReferenceAppAuthenticatedSettingsDisplayRouteImport } from './routes/reference-app/_authenticated/settings/display'
import { Route as ReferenceAppAuthenticatedSettingsAppearanceRouteImport } from './routes/reference-app/_authenticated/settings/appearance'
import { Route as ReferenceAppAuthenticatedSettingsAccountRouteImport } from './routes/reference-app/_authenticated/settings/account'
import { Route as ReferenceAppAuthenticatedErrorsErrorRouteImport } from './routes/reference-app/_authenticated/errors/$error'
import { Route as MainAuthenticatedSettingsNotificationsRouteImport } from './routes/main/_authenticated/settings/notifications'
import { Route as MainAuthenticatedSettingsDisplayRouteImport } from './routes/main/_authenticated/settings/display'
import { Route as MainAuthenticatedSettingsAppearanceRouteImport } from './routes/main/_authenticated/settings/appearance'
import { Route as MainAuthenticatedSettingsAccountRouteImport } from './routes/main/_authenticated/settings/account'
import { Route as MainAuthenticatedErrorsErrorRouteImport } from './routes/main/_authenticated/errors/$error'

const ReferenceAppRouteRoute = ReferenceAppRouteRouteImport.update({
  id: '/reference-app',
  path: '/reference-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceAppAuthenticatedRouteRoute =
  ReferenceAppAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => ReferenceAppRouteRoute,
  } as any)
const MainAuthenticatedRouteRoute = MainAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainRouteRoute,
} as any)
const ReferenceAppAuthenticatedIndexRoute =
  ReferenceAppAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const MainAuthenticatedIndexRoute = MainAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAuthenticatedRouteRoute,
} as any)
const ReferenceAppAuthenticatedDashboardRoute =
  ReferenceAppAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedComponentShowcaseRoute =
  ReferenceAppAuthenticatedComponentShowcaseRouteImport.update({
    id: '/component-showcase',
    path: '/component-showcase',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceApperrors503Route = ReferenceApperrors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceApperrors500Route = ReferenceApperrors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceApperrors404Route = ReferenceApperrors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceApperrors403Route = ReferenceApperrors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceApperrors401Route = ReferenceApperrors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceAppauthSignUpRoute = ReferenceAppauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceAppauthSignIn2Route = ReferenceAppauthSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceAppauthSignInRoute = ReferenceAppauthSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceAppauthOtpRoute = ReferenceAppauthOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => ReferenceAppRouteRoute,
} as any)
const ReferenceAppauthForgotPasswordRoute =
  ReferenceAppauthForgotPasswordRouteImport.update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => ReferenceAppRouteRoute,
  } as any)
const MainAuthenticatedNeo4jExplorerRoute =
  MainAuthenticatedNeo4jExplorerRouteImport.update({
    id: '/neo4j-explorer',
    path: '/neo4j-explorer',
    getParentRoute: () => MainAuthenticatedRouteRoute,
  } as any)
const MainAuthenticatedDashboardRoute =
  MainAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => MainAuthenticatedRouteRoute,
  } as any)
const Mainerrors503Route = Mainerrors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => MainRouteRoute,
} as any)
const Mainerrors500Route = Mainerrors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => MainRouteRoute,
} as any)
const Mainerrors404Route = Mainerrors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => MainRouteRoute,
} as any)
const Mainerrors403Route = Mainerrors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => MainRouteRoute,
} as any)
const Mainerrors401Route = Mainerrors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainauthSignUpRoute = MainauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainauthSignIn2Route = MainauthSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainauthSignInRoute = MainauthSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainauthOtpRoute = MainauthOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainauthForgotPasswordRoute = MainauthForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const ReferenceAppAuthenticatedSettingsRouteRoute =
  ReferenceAppAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const MainAuthenticatedSettingsRouteRoute =
  MainAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MainAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedUsersIndexRoute =
  ReferenceAppAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedTasksIndexRoute =
  ReferenceAppAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedSettingsIndexRoute =
  ReferenceAppAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReferenceAppAuthenticatedSettingsRouteRoute,
  } as any)
const ReferenceAppAuthenticatedKfzMarktplatzIndexRoute =
  ReferenceAppAuthenticatedKfzMarktplatzIndexRouteImport.update({
    id: '/kfz-marktplatz/',
    path: '/kfz-marktplatz/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedHelpCenterIndexRoute =
  ReferenceAppAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedChatsIndexRoute =
  ReferenceAppAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedAppsIndexRoute =
  ReferenceAppAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const MainAuthenticatedSettingsIndexRoute =
  MainAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAuthenticatedSettingsRouteRoute,
  } as any)
const MainAuthenticatedHelpCenterIndexRoute =
  MainAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => MainAuthenticatedRouteRoute,
  } as any)
const ReferenceAppAuthenticatedSettingsNotificationsRoute =
  ReferenceAppAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ReferenceAppAuthenticatedSettingsRouteRoute,
  } as any)
const ReferenceAppAuthenticatedSettingsDisplayRoute =
  ReferenceAppAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => ReferenceAppAuthenticatedSettingsRouteRoute,
  } as any)
const ReferenceAppAuthenticatedSettingsAppearanceRoute =
  ReferenceAppAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ReferenceAppAuthenticatedSettingsRouteRoute,
  } as any)
const ReferenceAppAuthenticatedSettingsAccountRoute =
  ReferenceAppAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ReferenceAppAuthenticatedSettingsRouteRoute,
  } as any)
const ReferenceAppAuthenticatedErrorsErrorRoute =
  ReferenceAppAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => ReferenceAppAuthenticatedRouteRoute,
  } as any)
const MainAuthenticatedSettingsNotificationsRoute =
  MainAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => MainAuthenticatedSettingsRouteRoute,
  } as any)
const MainAuthenticatedSettingsDisplayRoute =
  MainAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => MainAuthenticatedSettingsRouteRoute,
  } as any)
const MainAuthenticatedSettingsAppearanceRoute =
  MainAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => MainAuthenticatedSettingsRouteRoute,
  } as any)
const MainAuthenticatedSettingsAccountRoute =
  MainAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => MainAuthenticatedSettingsRouteRoute,
  } as any)
const MainAuthenticatedErrorsErrorRoute =
  MainAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => MainAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainAuthenticatedRouteRouteWithChildren
  '/reference-app': typeof ReferenceAppAuthenticatedRouteRouteWithChildren
  '/main/settings': typeof MainAuthenticatedSettingsRouteRouteWithChildren
  '/reference-app/settings': typeof ReferenceAppAuthenticatedSettingsRouteRouteWithChildren
  '/main/forgot-password': typeof MainauthForgotPasswordRoute
  '/main/otp': typeof MainauthOtpRoute
  '/main/sign-in': typeof MainauthSignInRoute
  '/main/sign-in-2': typeof MainauthSignIn2Route
  '/main/sign-up': typeof MainauthSignUpRoute
  '/main/401': typeof Mainerrors401Route
  '/main/403': typeof Mainerrors403Route
  '/main/404': typeof Mainerrors404Route
  '/main/500': typeof Mainerrors500Route
  '/main/503': typeof Mainerrors503Route
  '/main/dashboard': typeof MainAuthenticatedDashboardRoute
  '/main/neo4j-explorer': typeof MainAuthenticatedNeo4jExplorerRoute
  '/reference-app/forgot-password': typeof ReferenceAppauthForgotPasswordRoute
  '/reference-app/otp': typeof ReferenceAppauthOtpRoute
  '/reference-app/sign-in': typeof ReferenceAppauthSignInRoute
  '/reference-app/sign-in-2': typeof ReferenceAppauthSignIn2Route
  '/reference-app/sign-up': typeof ReferenceAppauthSignUpRoute
  '/reference-app/401': typeof ReferenceApperrors401Route
  '/reference-app/403': typeof ReferenceApperrors403Route
  '/reference-app/404': typeof ReferenceApperrors404Route
  '/reference-app/500': typeof ReferenceApperrors500Route
  '/reference-app/503': typeof ReferenceApperrors503Route
  '/reference-app/component-showcase': typeof ReferenceAppAuthenticatedComponentShowcaseRoute
  '/reference-app/dashboard': typeof ReferenceAppAuthenticatedDashboardRoute
  '/main/': typeof MainAuthenticatedIndexRoute
  '/reference-app/': typeof ReferenceAppAuthenticatedIndexRoute
  '/main/errors/$error': typeof MainAuthenticatedErrorsErrorRoute
  '/main/settings/account': typeof MainAuthenticatedSettingsAccountRoute
  '/main/settings/appearance': typeof MainAuthenticatedSettingsAppearanceRoute
  '/main/settings/display': typeof MainAuthenticatedSettingsDisplayRoute
  '/main/settings/notifications': typeof MainAuthenticatedSettingsNotificationsRoute
  '/reference-app/errors/$error': typeof ReferenceAppAuthenticatedErrorsErrorRoute
  '/reference-app/settings/account': typeof ReferenceAppAuthenticatedSettingsAccountRoute
  '/reference-app/settings/appearance': typeof ReferenceAppAuthenticatedSettingsAppearanceRoute
  '/reference-app/settings/display': typeof ReferenceAppAuthenticatedSettingsDisplayRoute
  '/reference-app/settings/notifications': typeof ReferenceAppAuthenticatedSettingsNotificationsRoute
  '/main/help-center': typeof MainAuthenticatedHelpCenterIndexRoute
  '/main/settings/': typeof MainAuthenticatedSettingsIndexRoute
  '/reference-app/apps': typeof ReferenceAppAuthenticatedAppsIndexRoute
  '/reference-app/chats': typeof ReferenceAppAuthenticatedChatsIndexRoute
  '/reference-app/help-center': typeof ReferenceAppAuthenticatedHelpCenterIndexRoute
  '/reference-app/kfz-marktplatz': typeof ReferenceAppAuthenticatedKfzMarktplatzIndexRoute
  '/reference-app/settings/': typeof ReferenceAppAuthenticatedSettingsIndexRoute
  '/reference-app/tasks': typeof ReferenceAppAuthenticatedTasksIndexRoute
  '/reference-app/users': typeof ReferenceAppAuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainAuthenticatedIndexRoute
  '/reference-app': typeof ReferenceAppAuthenticatedIndexRoute
  '/main/forgot-password': typeof MainauthForgotPasswordRoute
  '/main/otp': typeof MainauthOtpRoute
  '/main/sign-in': typeof MainauthSignInRoute
  '/main/sign-in-2': typeof MainauthSignIn2Route
  '/main/sign-up': typeof MainauthSignUpRoute
  '/main/401': typeof Mainerrors401Route
  '/main/403': typeof Mainerrors403Route
  '/main/404': typeof Mainerrors404Route
  '/main/500': typeof Mainerrors500Route
  '/main/503': typeof Mainerrors503Route
  '/main/dashboard': typeof MainAuthenticatedDashboardRoute
  '/main/neo4j-explorer': typeof MainAuthenticatedNeo4jExplorerRoute
  '/reference-app/forgot-password': typeof ReferenceAppauthForgotPasswordRoute
  '/reference-app/otp': typeof ReferenceAppauthOtpRoute
  '/reference-app/sign-in': typeof ReferenceAppauthSignInRoute
  '/reference-app/sign-in-2': typeof ReferenceAppauthSignIn2Route
  '/reference-app/sign-up': typeof ReferenceAppauthSignUpRoute
  '/reference-app/401': typeof ReferenceApperrors401Route
  '/reference-app/403': typeof ReferenceApperrors403Route
  '/reference-app/404': typeof ReferenceApperrors404Route
  '/reference-app/500': typeof ReferenceApperrors500Route
  '/reference-app/503': typeof ReferenceApperrors503Route
  '/reference-app/component-showcase': typeof ReferenceAppAuthenticatedComponentShowcaseRoute
  '/reference-app/dashboard': typeof ReferenceAppAuthenticatedDashboardRoute
  '/main/errors/$error': typeof MainAuthenticatedErrorsErrorRoute
  '/main/settings/account': typeof MainAuthenticatedSettingsAccountRoute
  '/main/settings/appearance': typeof MainAuthenticatedSettingsAppearanceRoute
  '/main/settings/display': typeof MainAuthenticatedSettingsDisplayRoute
  '/main/settings/notifications': typeof MainAuthenticatedSettingsNotificationsRoute
  '/reference-app/errors/$error': typeof ReferenceAppAuthenticatedErrorsErrorRoute
  '/reference-app/settings/account': typeof ReferenceAppAuthenticatedSettingsAccountRoute
  '/reference-app/settings/appearance': typeof ReferenceAppAuthenticatedSettingsAppearanceRoute
  '/reference-app/settings/display': typeof ReferenceAppAuthenticatedSettingsDisplayRoute
  '/reference-app/settings/notifications': typeof ReferenceAppAuthenticatedSettingsNotificationsRoute
  '/main/help-center': typeof MainAuthenticatedHelpCenterIndexRoute
  '/main/settings': typeof MainAuthenticatedSettingsIndexRoute
  '/reference-app/apps': typeof ReferenceAppAuthenticatedAppsIndexRoute
  '/reference-app/chats': typeof ReferenceAppAuthenticatedChatsIndexRoute
  '/reference-app/help-center': typeof ReferenceAppAuthenticatedHelpCenterIndexRoute
  '/reference-app/kfz-marktplatz': typeof ReferenceAppAuthenticatedKfzMarktplatzIndexRoute
  '/reference-app/settings': typeof ReferenceAppAuthenticatedSettingsIndexRoute
  '/reference-app/tasks': typeof ReferenceAppAuthenticatedTasksIndexRoute
  '/reference-app/users': typeof ReferenceAppAuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/reference-app': typeof ReferenceAppRouteRouteWithChildren
  '/main/_authenticated': typeof MainAuthenticatedRouteRouteWithChildren
  '/reference-app/_authenticated': typeof ReferenceAppAuthenticatedRouteRouteWithChildren
  '/main/_authenticated/settings': typeof MainAuthenticatedSettingsRouteRouteWithChildren
  '/reference-app/_authenticated/settings': typeof ReferenceAppAuthenticatedSettingsRouteRouteWithChildren
  '/main/(auth)/forgot-password': typeof MainauthForgotPasswordRoute
  '/main/(auth)/otp': typeof MainauthOtpRoute
  '/main/(auth)/sign-in': typeof MainauthSignInRoute
  '/main/(auth)/sign-in-2': typeof MainauthSignIn2Route
  '/main/(auth)/sign-up': typeof MainauthSignUpRoute
  '/main/(errors)/401': typeof Mainerrors401Route
  '/main/(errors)/403': typeof Mainerrors403Route
  '/main/(errors)/404': typeof Mainerrors404Route
  '/main/(errors)/500': typeof Mainerrors500Route
  '/main/(errors)/503': typeof Mainerrors503Route
  '/main/_authenticated/dashboard': typeof MainAuthenticatedDashboardRoute
  '/main/_authenticated/neo4j-explorer': typeof MainAuthenticatedNeo4jExplorerRoute
  '/reference-app/(auth)/forgot-password': typeof ReferenceAppauthForgotPasswordRoute
  '/reference-app/(auth)/otp': typeof ReferenceAppauthOtpRoute
  '/reference-app/(auth)/sign-in': typeof ReferenceAppauthSignInRoute
  '/reference-app/(auth)/sign-in-2': typeof ReferenceAppauthSignIn2Route
  '/reference-app/(auth)/sign-up': typeof ReferenceAppauthSignUpRoute
  '/reference-app/(errors)/401': typeof ReferenceApperrors401Route
  '/reference-app/(errors)/403': typeof ReferenceApperrors403Route
  '/reference-app/(errors)/404': typeof ReferenceApperrors404Route
  '/reference-app/(errors)/500': typeof ReferenceApperrors500Route
  '/reference-app/(errors)/503': typeof ReferenceApperrors503Route
  '/reference-app/_authenticated/component-showcase': typeof ReferenceAppAuthenticatedComponentShowcaseRoute
  '/reference-app/_authenticated/dashboard': typeof ReferenceAppAuthenticatedDashboardRoute
  '/main/_authenticated/': typeof MainAuthenticatedIndexRoute
  '/reference-app/_authenticated/': typeof ReferenceAppAuthenticatedIndexRoute
  '/main/_authenticated/errors/$error': typeof MainAuthenticatedErrorsErrorRoute
  '/main/_authenticated/settings/account': typeof MainAuthenticatedSettingsAccountRoute
  '/main/_authenticated/settings/appearance': typeof MainAuthenticatedSettingsAppearanceRoute
  '/main/_authenticated/settings/display': typeof MainAuthenticatedSettingsDisplayRoute
  '/main/_authenticated/settings/notifications': typeof MainAuthenticatedSettingsNotificationsRoute
  '/reference-app/_authenticated/errors/$error': typeof ReferenceAppAuthenticatedErrorsErrorRoute
  '/reference-app/_authenticated/settings/account': typeof ReferenceAppAuthenticatedSettingsAccountRoute
  '/reference-app/_authenticated/settings/appearance': typeof ReferenceAppAuthenticatedSettingsAppearanceRoute
  '/reference-app/_authenticated/settings/display': typeof ReferenceAppAuthenticatedSettingsDisplayRoute
  '/reference-app/_authenticated/settings/notifications': typeof ReferenceAppAuthenticatedSettingsNotificationsRoute
  '/main/_authenticated/help-center/': typeof MainAuthenticatedHelpCenterIndexRoute
  '/main/_authenticated/settings/': typeof MainAuthenticatedSettingsIndexRoute
  '/reference-app/_authenticated/apps/': typeof ReferenceAppAuthenticatedAppsIndexRoute
  '/reference-app/_authenticated/chats/': typeof ReferenceAppAuthenticatedChatsIndexRoute
  '/reference-app/_authenticated/help-center/': typeof ReferenceAppAuthenticatedHelpCenterIndexRoute
  '/reference-app/_authenticated/kfz-marktplatz/': typeof ReferenceAppAuthenticatedKfzMarktplatzIndexRoute
  '/reference-app/_authenticated/settings/': typeof ReferenceAppAuthenticatedSettingsIndexRoute
  '/reference-app/_authenticated/tasks/': typeof ReferenceAppAuthenticatedTasksIndexRoute
  '/reference-app/_authenticated/users/': typeof ReferenceAppAuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/reference-app'
    | '/main/settings'
    | '/reference-app/settings'
    | '/main/forgot-password'
    | '/main/otp'
    | '/main/sign-in'
    | '/main/sign-in-2'
    | '/main/sign-up'
    | '/main/401'
    | '/main/403'
    | '/main/404'
    | '/main/500'
    | '/main/503'
    | '/main/dashboard'
    | '/main/neo4j-explorer'
    | '/reference-app/forgot-password'
    | '/reference-app/otp'
    | '/reference-app/sign-in'
    | '/reference-app/sign-in-2'
    | '/reference-app/sign-up'
    | '/reference-app/401'
    | '/reference-app/403'
    | '/reference-app/404'
    | '/reference-app/500'
    | '/reference-app/503'
    | '/reference-app/component-showcase'
    | '/reference-app/dashboard'
    | '/main/'
    | '/reference-app/'
    | '/main/errors/$error'
    | '/main/settings/account'
    | '/main/settings/appearance'
    | '/main/settings/display'
    | '/main/settings/notifications'
    | '/reference-app/errors/$error'
    | '/reference-app/settings/account'
    | '/reference-app/settings/appearance'
    | '/reference-app/settings/display'
    | '/reference-app/settings/notifications'
    | '/main/help-center'
    | '/main/settings/'
    | '/reference-app/apps'
    | '/reference-app/chats'
    | '/reference-app/help-center'
    | '/reference-app/kfz-marktplatz'
    | '/reference-app/settings/'
    | '/reference-app/tasks'
    | '/reference-app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/reference-app'
    | '/main/forgot-password'
    | '/main/otp'
    | '/main/sign-in'
    | '/main/sign-in-2'
    | '/main/sign-up'
    | '/main/401'
    | '/main/403'
    | '/main/404'
    | '/main/500'
    | '/main/503'
    | '/main/dashboard'
    | '/main/neo4j-explorer'
    | '/reference-app/forgot-password'
    | '/reference-app/otp'
    | '/reference-app/sign-in'
    | '/reference-app/sign-in-2'
    | '/reference-app/sign-up'
    | '/reference-app/401'
    | '/reference-app/403'
    | '/reference-app/404'
    | '/reference-app/500'
    | '/reference-app/503'
    | '/reference-app/component-showcase'
    | '/reference-app/dashboard'
    | '/main/errors/$error'
    | '/main/settings/account'
    | '/main/settings/appearance'
    | '/main/settings/display'
    | '/main/settings/notifications'
    | '/reference-app/errors/$error'
    | '/reference-app/settings/account'
    | '/reference-app/settings/appearance'
    | '/reference-app/settings/display'
    | '/reference-app/settings/notifications'
    | '/main/help-center'
    | '/main/settings'
    | '/reference-app/apps'
    | '/reference-app/chats'
    | '/reference-app/help-center'
    | '/reference-app/kfz-marktplatz'
    | '/reference-app/settings'
    | '/reference-app/tasks'
    | '/reference-app/users'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/reference-app'
    | '/main/_authenticated'
    | '/reference-app/_authenticated'
    | '/main/_authenticated/settings'
    | '/reference-app/_authenticated/settings'
    | '/main/(auth)/forgot-password'
    | '/main/(auth)/otp'
    | '/main/(auth)/sign-in'
    | '/main/(auth)/sign-in-2'
    | '/main/(auth)/sign-up'
    | '/main/(errors)/401'
    | '/main/(errors)/403'
    | '/main/(errors)/404'
    | '/main/(errors)/500'
    | '/main/(errors)/503'
    | '/main/_authenticated/dashboard'
    | '/main/_authenticated/neo4j-explorer'
    | '/reference-app/(auth)/forgot-password'
    | '/reference-app/(auth)/otp'
    | '/reference-app/(auth)/sign-in'
    | '/reference-app/(auth)/sign-in-2'
    | '/reference-app/(auth)/sign-up'
    | '/reference-app/(errors)/401'
    | '/reference-app/(errors)/403'
    | '/reference-app/(errors)/404'
    | '/reference-app/(errors)/500'
    | '/reference-app/(errors)/503'
    | '/reference-app/_authenticated/component-showcase'
    | '/reference-app/_authenticated/dashboard'
    | '/main/_authenticated/'
    | '/reference-app/_authenticated/'
    | '/main/_authenticated/errors/$error'
    | '/main/_authenticated/settings/account'
    | '/main/_authenticated/settings/appearance'
    | '/main/_authenticated/settings/display'
    | '/main/_authenticated/settings/notifications'
    | '/reference-app/_authenticated/errors/$error'
    | '/reference-app/_authenticated/settings/account'
    | '/reference-app/_authenticated/settings/appearance'
    | '/reference-app/_authenticated/settings/display'
    | '/reference-app/_authenticated/settings/notifications'
    | '/main/_authenticated/help-center/'
    | '/main/_authenticated/settings/'
    | '/reference-app/_authenticated/apps/'
    | '/reference-app/_authenticated/chats/'
    | '/reference-app/_authenticated/help-center/'
    | '/reference-app/_authenticated/kfz-marktplatz/'
    | '/reference-app/_authenticated/settings/'
    | '/reference-app/_authenticated/tasks/'
    | '/reference-app/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ReferenceAppRouteRoute: typeof ReferenceAppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reference-app': {
      id: '/reference-app'
      path: '/reference-app'
      fullPath: '/reference-app'
      preLoaderRoute: typeof ReferenceAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-app/_authenticated': {
      id: '/reference-app/_authenticated'
      path: ''
      fullPath: '/reference-app'
      preLoaderRoute: typeof ReferenceAppAuthenticatedRouteRouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/main/_authenticated': {
      id: '/main/_authenticated'
      path: ''
      fullPath: '/main'
      preLoaderRoute: typeof MainAuthenticatedRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/reference-app/_authenticated/': {
      id: '/reference-app/_authenticated/'
      path: '/'
      fullPath: '/reference-app/'
      preLoaderRoute: typeof ReferenceAppAuthenticatedIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/main/_authenticated/': {
      id: '/main/_authenticated/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainAuthenticatedIndexRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/dashboard': {
      id: '/reference-app/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/reference-app/dashboard'
      preLoaderRoute: typeof ReferenceAppAuthenticatedDashboardRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/component-showcase': {
      id: '/reference-app/_authenticated/component-showcase'
      path: '/component-showcase'
      fullPath: '/reference-app/component-showcase'
      preLoaderRoute: typeof ReferenceAppAuthenticatedComponentShowcaseRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/(errors)/503': {
      id: '/reference-app/(errors)/503'
      path: '/503'
      fullPath: '/reference-app/503'
      preLoaderRoute: typeof ReferenceApperrors503RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(errors)/500': {
      id: '/reference-app/(errors)/500'
      path: '/500'
      fullPath: '/reference-app/500'
      preLoaderRoute: typeof ReferenceApperrors500RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(errors)/404': {
      id: '/reference-app/(errors)/404'
      path: '/404'
      fullPath: '/reference-app/404'
      preLoaderRoute: typeof ReferenceApperrors404RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(errors)/403': {
      id: '/reference-app/(errors)/403'
      path: '/403'
      fullPath: '/reference-app/403'
      preLoaderRoute: typeof ReferenceApperrors403RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(errors)/401': {
      id: '/reference-app/(errors)/401'
      path: '/401'
      fullPath: '/reference-app/401'
      preLoaderRoute: typeof ReferenceApperrors401RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(auth)/sign-up': {
      id: '/reference-app/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/reference-app/sign-up'
      preLoaderRoute: typeof ReferenceAppauthSignUpRouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(auth)/sign-in-2': {
      id: '/reference-app/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/reference-app/sign-in-2'
      preLoaderRoute: typeof ReferenceAppauthSignIn2RouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(auth)/sign-in': {
      id: '/reference-app/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/reference-app/sign-in'
      preLoaderRoute: typeof ReferenceAppauthSignInRouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(auth)/otp': {
      id: '/reference-app/(auth)/otp'
      path: '/otp'
      fullPath: '/reference-app/otp'
      preLoaderRoute: typeof ReferenceAppauthOtpRouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/reference-app/(auth)/forgot-password': {
      id: '/reference-app/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/reference-app/forgot-password'
      preLoaderRoute: typeof ReferenceAppauthForgotPasswordRouteImport
      parentRoute: typeof ReferenceAppRouteRoute
    }
    '/main/_authenticated/neo4j-explorer': {
      id: '/main/_authenticated/neo4j-explorer'
      path: '/neo4j-explorer'
      fullPath: '/main/neo4j-explorer'
      preLoaderRoute: typeof MainAuthenticatedNeo4jExplorerRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
    '/main/_authenticated/dashboard': {
      id: '/main/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/main/dashboard'
      preLoaderRoute: typeof MainAuthenticatedDashboardRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
    '/main/(errors)/503': {
      id: '/main/(errors)/503'
      path: '/503'
      fullPath: '/main/503'
      preLoaderRoute: typeof Mainerrors503RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(errors)/500': {
      id: '/main/(errors)/500'
      path: '/500'
      fullPath: '/main/500'
      preLoaderRoute: typeof Mainerrors500RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(errors)/404': {
      id: '/main/(errors)/404'
      path: '/404'
      fullPath: '/main/404'
      preLoaderRoute: typeof Mainerrors404RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(errors)/403': {
      id: '/main/(errors)/403'
      path: '/403'
      fullPath: '/main/403'
      preLoaderRoute: typeof Mainerrors403RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(errors)/401': {
      id: '/main/(errors)/401'
      path: '/401'
      fullPath: '/main/401'
      preLoaderRoute: typeof Mainerrors401RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(auth)/sign-up': {
      id: '/main/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/main/sign-up'
      preLoaderRoute: typeof MainauthSignUpRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(auth)/sign-in-2': {
      id: '/main/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/main/sign-in-2'
      preLoaderRoute: typeof MainauthSignIn2RouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(auth)/sign-in': {
      id: '/main/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/main/sign-in'
      preLoaderRoute: typeof MainauthSignInRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(auth)/otp': {
      id: '/main/(auth)/otp'
      path: '/otp'
      fullPath: '/main/otp'
      preLoaderRoute: typeof MainauthOtpRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/(auth)/forgot-password': {
      id: '/main/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/main/forgot-password'
      preLoaderRoute: typeof MainauthForgotPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/reference-app/_authenticated/settings': {
      id: '/reference-app/_authenticated/settings'
      path: '/settings'
      fullPath: '/reference-app/settings'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/main/_authenticated/settings': {
      id: '/main/_authenticated/settings'
      path: '/settings'
      fullPath: '/main/settings'
      preLoaderRoute: typeof MainAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/users/': {
      id: '/reference-app/_authenticated/users/'
      path: '/users'
      fullPath: '/reference-app/users'
      preLoaderRoute: typeof ReferenceAppAuthenticatedUsersIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/tasks/': {
      id: '/reference-app/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/reference-app/tasks'
      preLoaderRoute: typeof ReferenceAppAuthenticatedTasksIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/settings/': {
      id: '/reference-app/_authenticated/settings/'
      path: '/'
      fullPath: '/reference-app/settings/'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedSettingsRouteRoute
    }
    '/reference-app/_authenticated/kfz-marktplatz/': {
      id: '/reference-app/_authenticated/kfz-marktplatz/'
      path: '/kfz-marktplatz'
      fullPath: '/reference-app/kfz-marktplatz'
      preLoaderRoute: typeof ReferenceAppAuthenticatedKfzMarktplatzIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/help-center/': {
      id: '/reference-app/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/reference-app/help-center'
      preLoaderRoute: typeof ReferenceAppAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/chats/': {
      id: '/reference-app/_authenticated/chats/'
      path: '/chats'
      fullPath: '/reference-app/chats'
      preLoaderRoute: typeof ReferenceAppAuthenticatedChatsIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/apps/': {
      id: '/reference-app/_authenticated/apps/'
      path: '/apps'
      fullPath: '/reference-app/apps'
      preLoaderRoute: typeof ReferenceAppAuthenticatedAppsIndexRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/main/_authenticated/settings/': {
      id: '/main/_authenticated/settings/'
      path: '/'
      fullPath: '/main/settings/'
      preLoaderRoute: typeof MainAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof MainAuthenticatedSettingsRouteRoute
    }
    '/main/_authenticated/help-center/': {
      id: '/main/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/main/help-center'
      preLoaderRoute: typeof MainAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
    '/reference-app/_authenticated/settings/notifications': {
      id: '/reference-app/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/reference-app/settings/notifications'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedSettingsRouteRoute
    }
    '/reference-app/_authenticated/settings/display': {
      id: '/reference-app/_authenticated/settings/display'
      path: '/display'
      fullPath: '/reference-app/settings/display'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedSettingsRouteRoute
    }
    '/reference-app/_authenticated/settings/appearance': {
      id: '/reference-app/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/reference-app/settings/appearance'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedSettingsRouteRoute
    }
    '/reference-app/_authenticated/settings/account': {
      id: '/reference-app/_authenticated/settings/account'
      path: '/account'
      fullPath: '/reference-app/settings/account'
      preLoaderRoute: typeof ReferenceAppAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedSettingsRouteRoute
    }
    '/reference-app/_authenticated/errors/$error': {
      id: '/reference-app/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/reference-app/errors/$error'
      preLoaderRoute: typeof ReferenceAppAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof ReferenceAppAuthenticatedRouteRoute
    }
    '/main/_authenticated/settings/notifications': {
      id: '/main/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/main/settings/notifications'
      preLoaderRoute: typeof MainAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof MainAuthenticatedSettingsRouteRoute
    }
    '/main/_authenticated/settings/display': {
      id: '/main/_authenticated/settings/display'
      path: '/display'
      fullPath: '/main/settings/display'
      preLoaderRoute: typeof MainAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof MainAuthenticatedSettingsRouteRoute
    }
    '/main/_authenticated/settings/appearance': {
      id: '/main/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/main/settings/appearance'
      preLoaderRoute: typeof MainAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof MainAuthenticatedSettingsRouteRoute
    }
    '/main/_authenticated/settings/account': {
      id: '/main/_authenticated/settings/account'
      path: '/account'
      fullPath: '/main/settings/account'
      preLoaderRoute: typeof MainAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof MainAuthenticatedSettingsRouteRoute
    }
    '/main/_authenticated/errors/$error': {
      id: '/main/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/main/errors/$error'
      preLoaderRoute: typeof MainAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof MainAuthenticatedRouteRoute
    }
  }
}

interface MainAuthenticatedSettingsRouteRouteChildren {
  MainAuthenticatedSettingsAccountRoute: typeof MainAuthenticatedSettingsAccountRoute
  MainAuthenticatedSettingsAppearanceRoute: typeof MainAuthenticatedSettingsAppearanceRoute
  MainAuthenticatedSettingsDisplayRoute: typeof MainAuthenticatedSettingsDisplayRoute
  MainAuthenticatedSettingsNotificationsRoute: typeof MainAuthenticatedSettingsNotificationsRoute
  MainAuthenticatedSettingsIndexRoute: typeof MainAuthenticatedSettingsIndexRoute
}

const MainAuthenticatedSettingsRouteRouteChildren: MainAuthenticatedSettingsRouteRouteChildren =
  {
    MainAuthenticatedSettingsAccountRoute:
      MainAuthenticatedSettingsAccountRoute,
    MainAuthenticatedSettingsAppearanceRoute:
      MainAuthenticatedSettingsAppearanceRoute,
    MainAuthenticatedSettingsDisplayRoute:
      MainAuthenticatedSettingsDisplayRoute,
    MainAuthenticatedSettingsNotificationsRoute:
      MainAuthenticatedSettingsNotificationsRoute,
    MainAuthenticatedSettingsIndexRoute: MainAuthenticatedSettingsIndexRoute,
  }

const MainAuthenticatedSettingsRouteRouteWithChildren =
  MainAuthenticatedSettingsRouteRoute._addFileChildren(
    MainAuthenticatedSettingsRouteRouteChildren,
  )

interface MainAuthenticatedRouteRouteChildren {
  MainAuthenticatedSettingsRouteRoute: typeof MainAuthenticatedSettingsRouteRouteWithChildren
  MainAuthenticatedDashboardRoute: typeof MainAuthenticatedDashboardRoute
  MainAuthenticatedNeo4jExplorerRoute: typeof MainAuthenticatedNeo4jExplorerRoute
  MainAuthenticatedIndexRoute: typeof MainAuthenticatedIndexRoute
  MainAuthenticatedErrorsErrorRoute: typeof MainAuthenticatedErrorsErrorRoute
  MainAuthenticatedHelpCenterIndexRoute: typeof MainAuthenticatedHelpCenterIndexRoute
}

const MainAuthenticatedRouteRouteChildren: MainAuthenticatedRouteRouteChildren =
  {
    MainAuthenticatedSettingsRouteRoute:
      MainAuthenticatedSettingsRouteRouteWithChildren,
    MainAuthenticatedDashboardRoute: MainAuthenticatedDashboardRoute,
    MainAuthenticatedNeo4jExplorerRoute: MainAuthenticatedNeo4jExplorerRoute,
    MainAuthenticatedIndexRoute: MainAuthenticatedIndexRoute,
    MainAuthenticatedErrorsErrorRoute: MainAuthenticatedErrorsErrorRoute,
    MainAuthenticatedHelpCenterIndexRoute:
      MainAuthenticatedHelpCenterIndexRoute,
  }

const MainAuthenticatedRouteRouteWithChildren =
  MainAuthenticatedRouteRoute._addFileChildren(
    MainAuthenticatedRouteRouteChildren,
  )

interface MainRouteRouteChildren {
  MainAuthenticatedRouteRoute: typeof MainAuthenticatedRouteRouteWithChildren
  MainauthForgotPasswordRoute: typeof MainauthForgotPasswordRoute
  MainauthOtpRoute: typeof MainauthOtpRoute
  MainauthSignInRoute: typeof MainauthSignInRoute
  MainauthSignIn2Route: typeof MainauthSignIn2Route
  MainauthSignUpRoute: typeof MainauthSignUpRoute
  Mainerrors401Route: typeof Mainerrors401Route
  Mainerrors403Route: typeof Mainerrors403Route
  Mainerrors404Route: typeof Mainerrors404Route
  Mainerrors500Route: typeof Mainerrors500Route
  Mainerrors503Route: typeof Mainerrors503Route
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthenticatedRouteRoute: MainAuthenticatedRouteRouteWithChildren,
  MainauthForgotPasswordRoute: MainauthForgotPasswordRoute,
  MainauthOtpRoute: MainauthOtpRoute,
  MainauthSignInRoute: MainauthSignInRoute,
  MainauthSignIn2Route: MainauthSignIn2Route,
  MainauthSignUpRoute: MainauthSignUpRoute,
  Mainerrors401Route: Mainerrors401Route,
  Mainerrors403Route: Mainerrors403Route,
  Mainerrors404Route: Mainerrors404Route,
  Mainerrors500Route: Mainerrors500Route,
  Mainerrors503Route: Mainerrors503Route,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ReferenceAppAuthenticatedSettingsRouteRouteChildren {
  ReferenceAppAuthenticatedSettingsAccountRoute: typeof ReferenceAppAuthenticatedSettingsAccountRoute
  ReferenceAppAuthenticatedSettingsAppearanceRoute: typeof ReferenceAppAuthenticatedSettingsAppearanceRoute
  ReferenceAppAuthenticatedSettingsDisplayRoute: typeof ReferenceAppAuthenticatedSettingsDisplayRoute
  ReferenceAppAuthenticatedSettingsNotificationsRoute: typeof ReferenceAppAuthenticatedSettingsNotificationsRoute
  ReferenceAppAuthenticatedSettingsIndexRoute: typeof ReferenceAppAuthenticatedSettingsIndexRoute
}

const ReferenceAppAuthenticatedSettingsRouteRouteChildren: ReferenceAppAuthenticatedSettingsRouteRouteChildren =
  {
    ReferenceAppAuthenticatedSettingsAccountRoute:
      ReferenceAppAuthenticatedSettingsAccountRoute,
    ReferenceAppAuthenticatedSettingsAppearanceRoute:
      ReferenceAppAuthenticatedSettingsAppearanceRoute,
    ReferenceAppAuthenticatedSettingsDisplayRoute:
      ReferenceAppAuthenticatedSettingsDisplayRoute,
    ReferenceAppAuthenticatedSettingsNotificationsRoute:
      ReferenceAppAuthenticatedSettingsNotificationsRoute,
    ReferenceAppAuthenticatedSettingsIndexRoute:
      ReferenceAppAuthenticatedSettingsIndexRoute,
  }

const ReferenceAppAuthenticatedSettingsRouteRouteWithChildren =
  ReferenceAppAuthenticatedSettingsRouteRoute._addFileChildren(
    ReferenceAppAuthenticatedSettingsRouteRouteChildren,
  )

interface ReferenceAppAuthenticatedRouteRouteChildren {
  ReferenceAppAuthenticatedSettingsRouteRoute: typeof ReferenceAppAuthenticatedSettingsRouteRouteWithChildren
  ReferenceAppAuthenticatedComponentShowcaseRoute: typeof ReferenceAppAuthenticatedComponentShowcaseRoute
  ReferenceAppAuthenticatedDashboardRoute: typeof ReferenceAppAuthenticatedDashboardRoute
  ReferenceAppAuthenticatedIndexRoute: typeof ReferenceAppAuthenticatedIndexRoute
  ReferenceAppAuthenticatedErrorsErrorRoute: typeof ReferenceAppAuthenticatedErrorsErrorRoute
  ReferenceAppAuthenticatedAppsIndexRoute: typeof ReferenceAppAuthenticatedAppsIndexRoute
  ReferenceAppAuthenticatedChatsIndexRoute: typeof ReferenceAppAuthenticatedChatsIndexRoute
  ReferenceAppAuthenticatedHelpCenterIndexRoute: typeof ReferenceAppAuthenticatedHelpCenterIndexRoute
  ReferenceAppAuthenticatedKfzMarktplatzIndexRoute: typeof ReferenceAppAuthenticatedKfzMarktplatzIndexRoute
  ReferenceAppAuthenticatedTasksIndexRoute: typeof ReferenceAppAuthenticatedTasksIndexRoute
  ReferenceAppAuthenticatedUsersIndexRoute: typeof ReferenceAppAuthenticatedUsersIndexRoute
}

const ReferenceAppAuthenticatedRouteRouteChildren: ReferenceAppAuthenticatedRouteRouteChildren =
  {
    ReferenceAppAuthenticatedSettingsRouteRoute:
      ReferenceAppAuthenticatedSettingsRouteRouteWithChildren,
    ReferenceAppAuthenticatedComponentShowcaseRoute:
      ReferenceAppAuthenticatedComponentShowcaseRoute,
    ReferenceAppAuthenticatedDashboardRoute:
      ReferenceAppAuthenticatedDashboardRoute,
    ReferenceAppAuthenticatedIndexRoute: ReferenceAppAuthenticatedIndexRoute,
    ReferenceAppAuthenticatedErrorsErrorRoute:
      ReferenceAppAuthenticatedErrorsErrorRoute,
    ReferenceAppAuthenticatedAppsIndexRoute:
      ReferenceAppAuthenticatedAppsIndexRoute,
    ReferenceAppAuthenticatedChatsIndexRoute:
      ReferenceAppAuthenticatedChatsIndexRoute,
    ReferenceAppAuthenticatedHelpCenterIndexRoute:
      ReferenceAppAuthenticatedHelpCenterIndexRoute,
    ReferenceAppAuthenticatedKfzMarktplatzIndexRoute:
      ReferenceAppAuthenticatedKfzMarktplatzIndexRoute,
    ReferenceAppAuthenticatedTasksIndexRoute:
      ReferenceAppAuthenticatedTasksIndexRoute,
    ReferenceAppAuthenticatedUsersIndexRoute:
      ReferenceAppAuthenticatedUsersIndexRoute,
  }

const ReferenceAppAuthenticatedRouteRouteWithChildren =
  ReferenceAppAuthenticatedRouteRoute._addFileChildren(
    ReferenceAppAuthenticatedRouteRouteChildren,
  )

interface ReferenceAppRouteRouteChildren {
  ReferenceAppAuthenticatedRouteRoute: typeof ReferenceAppAuthenticatedRouteRouteWithChildren
  ReferenceAppauthForgotPasswordRoute: typeof ReferenceAppauthForgotPasswordRoute
  ReferenceAppauthOtpRoute: typeof ReferenceAppauthOtpRoute
  ReferenceAppauthSignInRoute: typeof ReferenceAppauthSignInRoute
  ReferenceAppauthSignIn2Route: typeof ReferenceAppauthSignIn2Route
  ReferenceAppauthSignUpRoute: typeof ReferenceAppauthSignUpRoute
  ReferenceApperrors401Route: typeof ReferenceApperrors401Route
  ReferenceApperrors403Route: typeof ReferenceApperrors403Route
  ReferenceApperrors404Route: typeof ReferenceApperrors404Route
  ReferenceApperrors500Route: typeof ReferenceApperrors500Route
  ReferenceApperrors503Route: typeof ReferenceApperrors503Route
}

const ReferenceAppRouteRouteChildren: ReferenceAppRouteRouteChildren = {
  ReferenceAppAuthenticatedRouteRoute:
    ReferenceAppAuthenticatedRouteRouteWithChildren,
  ReferenceAppauthForgotPasswordRoute: ReferenceAppauthForgotPasswordRoute,
  ReferenceAppauthOtpRoute: ReferenceAppauthOtpRoute,
  ReferenceAppauthSignInRoute: ReferenceAppauthSignInRoute,
  ReferenceAppauthSignIn2Route: ReferenceAppauthSignIn2Route,
  ReferenceAppauthSignUpRoute: ReferenceAppauthSignUpRoute,
  ReferenceApperrors401Route: ReferenceApperrors401Route,
  ReferenceApperrors403Route: ReferenceApperrors403Route,
  ReferenceApperrors404Route: ReferenceApperrors404Route,
  ReferenceApperrors500Route: ReferenceApperrors500Route,
  ReferenceApperrors503Route: ReferenceApperrors503Route,
}

const ReferenceAppRouteRouteWithChildren =
  ReferenceAppRouteRoute._addFileChildren(ReferenceAppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  ReferenceAppRouteRoute: ReferenceAppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
