services:
  neo4j:
    image: neo4j:5-community
    container_name: neo4j-explorer-db
    ports:
      - '7687:7687'
      - '7474:7474'
    environment:
      NEO4J_AUTH: neo4j/neo4jneo4j
      NEO4J_PLUGINS: '[]'
    volumes:
      - ./db:/data
      - ../Ontology_UWWB/cypher:/import
